-- Facilities domain: rooms/spaces, bookings with overlap prevention and approval workflow
-- Run after organizations and users exist.

CREATE TABLE IF NOT EXISTS `facilities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `location` VARCHAR(500) NULL,
  `capacity` INT UNSIGNED NULL,
  `image` VARCHAR(500) NULL,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `allow_member_booking` BOOLEAN NOT NULL DEFAULT TRUE,
  `allow_guest_booking` BOOLEAN NOT NULL DEFAULT TRUE,
  `member_max_duration_minutes` INT UNSIGNED NOT NULL DEFAULT 120,
  `member_advance_days` INT UNSIGNED NOT NULL DEFAULT 30,
  `member_operating_hours` JSON NULL COMMENT 'day 0-6 Sun-Sat => {open, close}',
  `guest_max_duration_minutes` INT UNSIGNED NOT NULL DEFAULT 120,
  `guest_advance_days` INT UNSIGNED NOT NULL DEFAULT 14,
  `guest_operating_hours` JSON NULL,
  `staff_max_duration_minutes` INT UNSIGNED NOT NULL DEFAULT 480,
  `staff_advance_days` INT UNSIGNED NOT NULL DEFAULT 90,
  `min_duration_minutes` INT UNSIGNED NOT NULL DEFAULT 30,
  `buffer_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
  `slot_increment_minutes` INT UNSIGNED NOT NULL DEFAULT 30,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_org_slug` (`organization_id`, `slug`),
  INDEX `idx_org_status` (`organization_id`, `status`),
  FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `facility_bookings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `facility_id` INT UNSIGNED NOT NULL,
  `booked_by_user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `purpose` TEXT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `status` ENUM('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `booked_via` ENUM('guest','portal','admin') NOT NULL DEFAULT 'portal',
  `reviewed_by` INT UNSIGNED NULL,
  `reviewed_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_facility_range` (`facility_id`, `start_datetime`, `end_datetime`, `status`),
  INDEX `idx_org_status` (`organization_id`, `status`),
  INDEX `idx_user` (`booked_by_user_id`),
  FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`facility_id`) REFERENCES `facilities` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`booked_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
